# Setup
title:            ARPFIC
tagline:          'Attempts on organ making'
url:              https://arpfic.github.io
baseurl:          ''
paginate:         5
background:       https://arpfic.github.io/img/49.jpg
description:
  top:  'Il est &agrave; se demander parfois si nos usages ne sont pas insens&eacute;. D&apos;autres feraient aussi bien l&apos;affaire, peut-&ecirc;tre. Il suffirait d&apos;essayer.'
  center:  'Qu&apos;est-ce que j&apos;ai ? Ce sont de folles pens&eacute;es. Il faut de la discipline. <i>(Un temps.)</i>'
  bottom: 'Tentatives autour d&apos;un orgue excentr&eacute;. Il y a aussi <a href="www.violonaroue.fr" target="_blank">violonaroue.fr</a> &copy; 2020 ARPFIC'

# About and contact
author:
  name:           'Damien L.'
  url:            https://arpfic.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/arpfic/arpfic.github.io
